### ISSUE TITLE
Feat: 동시 탭 제스처 인식, 동시 탭 제스처 싱크 맞추기

### ISSUE THREAD

**Issue by yeniful** [yeniful/kko_okk#100]
- simultaneous gesture가 동시에 탭하는 제스처를 의미하는 줄 알았는데, gesture 중첩을 위한 기능이었네요. 부모 리스트와 아이 리스트의 셀 메모리를 찍어봤을 때 같은 메모리로 나와서(ㅠㅠ) 인스턴스가 아닌 위에 덮힌 제스처로 셀을 구분하는 방식이나 UUID가 같은지를 기준으로 해결해야할 것 같습니다. Filter는 새로운 인스턴스를 찍어내기보단 이름 그대로 걸러서 보여주는게 아닐까 싶어요.

- 제스처 싱크를 맞추기 위한 여유시간을 고려해야합니다. Timer를 이용하려고 했는데 적절한 방식인지 확신이 안서서 멘토님들께 더 좋은 방향에 대해서 조언을 구해보도록 하겠습니다.

**Comment by garlicvread** [comment]
아 물리메모리 주소가 같아요? ㄷㄷ
