### ISSUE TITLE
Fix: Board Tapbar 버그 수정 

### ISSUE THREAD

**Issue by yeniful** [yeniful/kko_okk#117]
Uploading Simulator Screen Recording - iPad Pro (12.9-inch) (5th generation) - 2022-06-16 at 11.37.34.mp4…

**Comment by yeniful** [comment]
버그킬러 버킬이 았다면... 버그메이커 예니가 잇다...

**Comment by garlicvread** [comment]
ㅋㅋㅋㅋㅋㅋ
