### ISSUE TITLE
Feat: '부모님이 지켜요', '아이가 지켜요' 옆에 있는 'o' (색상) 추가하기 ✅

### ISSUE THREAD

**Issue by LeeSungNo-ian** [yeniful/kko_okk#154]
<img width="235" alt="image" src="https://user-images.githubusercontent.com/78950704/174263794-8179e961-5aab-4b59-94a7-385a8c53a787.png">

<img width="226" alt="image" src="https://user-images.githubusercontent.com/78950704/174263825-c0a6a22b-f610-4a41-9cdb-ffda1a89fe3f.png">

해야합니다..!

**Comment by yeniful** [comment]
UI 수정할 때 손봤습니다! 한꺼번에 Push하겠습니다...!
