### ISSUE TITLE
Feat: '+' 버튼 위에 있는 지문 모양 추가하기

### ISSUE THREAD

**Issue by LeeSungNo-ian** [yeniful/kko_okk#156]
<img width="71" alt="image" src="https://user-images.githubusercontent.com/78950704/174264120-d48d520f-f5d5-4ea0-9eaa-b1ad9c3be8a3.png">

<img width="70" alt="image" src="https://user-images.githubusercontent.com/78950704/174264144-3f7c7dfd-0da3-4cad-bd1a-388526cd86ec.png">

해야돼요!!

**Comment by garlicvread** [comment]
#173 으로 해결했어요!
