### ISSUE TITLE
Fix: 약속 삭제시 발생하는 에러 🐞 ✅

### ISSUE THREAD

**Issue by yeniful** [yeniful/kko_okk#164]
![image](https://user-images.githubusercontent.com/77262576/174354323-a95f970c-12e6-4b73-b221-c1e861669dc3.png)

<img width="1182" alt="스크린샷 2022-06-18 오전 3 09 09" src="https://user-images.githubusercontent.com/77262576/174354291-2c697223-8097-4024-b904-7fc5f2b80752.png">

**Comment by yeniful** [comment]
생각해보니 레이먼드가 이미 언급해주셨던 부분이었던 것 같음!

**Comment by garlicvread** [comment]
흑... 내껀데...
