### ISSUE TITLE
Fix: isDone 체크 마크가 다른 뷰에 다녀오면 사라집니다. 🐞

### ISSUE THREAD

**Issue by Valentino1994** [yeniful/kko_okk#169]
아마도 Path 자체가 isDone일때 1로 안되어 있는듯 해요

https://user-images.githubusercontent.com/77421835/174435310-87a306f7-f43e-46aa-b9fa-fc549a060473.mov

**Comment by yeniful** [comment]
앗 확인해보고 수정하겠습니다!!

**Comment by yeniful** [comment]
서담이 #128 에서 언급했던 문제네요!
