### ISSUE TITLE
Fix: UI 디자인 디테일

### ISSUE THREAD

**Issue by yeniful** [yeniful/kko_okk#171]
<img width="715" alt="스크린샷 2022-06-18 오후 8 56 43" src="https://user-images.githubusercontent.com/77262576/174436364-df6a948e-91c1-4b8c-8b25-bbf17dea70d4.png">

![simulator_screenshot_7191AD31-0A06-4FA6-9E9D-FEFA809CD72F](https://user-images.githubusercontent.com/77262576/174436670-bf656fbb-e4c6-4807-976e-1a4a51b5773c.png)

12.9인치 기준의 디자인과 12.9인치 시뮬레이터 화면인데 가시적인 차이가 보입니다.
전반적으로 레이아웃을 맞추기 위한 패딩값 조절이 필요할 것 같은데 보드 내부에 frame으로 지정한 값들이 문제가 될 수도 있을것 같아요.
- 테이블 간 간격 조절
- 탭 밑에 선택된 탭을 나타내는 표시도 추가해야합니다 (아래 디바이더와의 간격을 조금 줄여야합니다) -> @yeniful  Done ✅
- 설정 아이콘도 추가해야 합니다.
- 버튼 뒤에 지문이미지를 넣어야 합니다. (#114) -> @garlicvread Done ✅

**Comment by LeeSungNo-ian** [comment]
UI 용사 예니..

**Comment by garlicvread** [comment]
버튼 뒤 지문... 은 아니고 아무튼 핑거팁 모양은 넣었습니다. #173 으로 해결했음.
