### ISSUE TITLE
BE/PromiseModel

### ISSUE THREAD

**Issue by Valentino1994** [yeniful/kko_okk#9]
약속 관련 모델을 만들겠습니다. 테이블 모델링은 아래와 같습니다.

![image](https://user-images.githubusercontent.com/77421835/171315351-c5f355b0-2516-44d9-a4c8-13b966100641.png)

**Comment by garlicvread** [comment]
근데 이거 제목/메모 하나로 통합한다는 얘기가 있었던 것 같기도 하고...?
일단 테이블에 만들어 놓고 쓸지 말지 나중에 바꾸면 되니 상관 없긴 하겠네요!
